import Foundation

/// One entry of a core vocabulary list. Fields mirror
/// vocabulary/<language>_core_vocabulary.json, generated by
/// vocabulary/build_vocabulary.py; nothing here is edited by hand.
///
/// `headword` is unique within a list (checked by the build script) and is the
/// key for progress and on-screen tiles. `lemma` is not unique: Latin has
/// homographs such as the adverb and the verb both spelled adeō.
struct VocabularyEntry: Codable, Identifiable, Hashable {
    let rank: Int
    let headword: String
    let lemma: String
    let definition: String
    let pos: String
    let group: String

    var id: String { headword }
}

/// The JSON file's top level.
struct VocabularyList: Codable {
    let language: String
    let source: String
    let url: String
    let license: String
    let count: Int
    let entries: [VocabularyEntry]
}

/// A contiguous slice of a list in frequency order, or the whole list.
struct VocabularySet: Identifiable, Hashable {
    let label: String
    let entries: [VocabularyEntry]

    var id: String { label }
}

/// Loads the bundled vocabulary lists.
enum VocabularyData {
    static let setSize = 25

    /// Display names, in picker order. Lowercased, each is the key into `files`.
    static let availableLanguages = ["Greek", "Latin"]

    private static let files = [
        "greek": "greek_core_vocabulary",
        "latin": "latin_core_vocabulary",
    ]

    private static var cache: [String: [VocabularyEntry]] = [:]
    private static let lock = NSLock()

    /// The list for a language key ("greek", "latin"). Empty if the resource
    /// is missing from the bundle or fails to decode; the error is logged.
    static func entries(for language: String) -> [VocabularyEntry] {
        lock.lock()
        defer { lock.unlock() }
        if let cached = cache[language] { return cached }
        guard let name = files[language] else {
            NSLog("VocabularyData: no vocabulary list for language '%@'", language)
            return []
        }
        guard let url = Bundle.main.url(forResource: name, withExtension: "json") else {
            NSLog("VocabularyData: %@.json is not in the app bundle", name)
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            let list = try JSONDecoder().decode(VocabularyList.self, from: data)
            let headwords = Set(list.entries.map { $0.headword })
            if headwords.count != list.entries.count {
                NSLog("VocabularyData: %@.json has duplicate headwords", name)
                return []
            }
            cache[language] = list.entries
            return list.entries
        } catch {
            NSLog("VocabularyData: failed to load %@.json: %@", name, String(describing: error))
            return []
        }
    }

    /// Sets of `setSize` words in list order (the list is sorted by frequency
    /// rank), followed by one set holding every word. Labels use list positions
    /// rather than rank values because the sources assign some ranks twice.
    static func sets(for language: String) -> [VocabularySet] {
        let all = entries(for: language)
        var sets: [VocabularySet] = []
        var start = 0
        while start < all.count {
            let end = min(start + setSize, all.count)
            sets.append(VocabularySet(label: "Words \(start + 1)–\(end)", entries: Array(all[start..<end])))
            start = end
        }
        sets.append(VocabularySet(label: "All \(all.count) words", entries: all))
        return sets
    }
}

/// Persists which words the learner has matched in a perfect round, per
/// language, as an array of headwords in UserDefaults. Mirrors the Android
/// `VocabularyProgress` SharedPreferences store.
enum VocabularyProgress {
    private static func key(_ language: String) -> String { "vocabulary_mastered_\(language)" }

    static func mastered(_ language: String) -> Set<String> {
        Set(UserDefaults.standard.stringArray(forKey: key(language)) ?? [])
    }

    static func addMastered(_ language: String, _ headwords: [String]) {
        let merged = mastered(language).union(headwords)
        UserDefaults.standard.set(Array(merged), forKey: key(language))
    }

    static func clear(_ language: String) {
        UserDefaults.standard.removeObject(forKey: key(language))
    }
}
