version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../data-prep/perseus_texts_full.db:/data/perseus_texts_full.db:ro
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_PATH=/data/perseus_texts_full.db
    command: npm start
