package com.classicsviewer.app.vocabulary

import android.content.Context
import org.json.JSONObject

/**
 * One entry of a core vocabulary list. Fields mirror vocabulary/<language>_core_vocabulary.json.
 * [headword] is unique within a list (checked by the build script) and is the key for
 * progress and on-screen tiles; [lemma] is not unique (Latin has homographs such as
 * the adverb and the verb both spelled adeō).
 */
data class VocabularyEntry(
    val rank: Int,
    val headword: String,
    val lemma: String,
    val definition: String,
    val pos: String,
    val group: String
)

/** A contiguous slice of a list in frequency order, or the whole list. */
data class VocabularySet(
    val label: String,
    val entries: List<VocabularyEntry>
)

/**
 * Loads the bundled vocabulary lists from assets/vocabulary/. The JSON files are
 * generated by vocabulary/build_vocabulary.py; nothing here is edited by hand.
 */
object VocabularyData {

    const val SET_SIZE = 25

    /** Display names, in picker order. Lowercased, each is the key into [assetFiles]. */
    val availableLanguages = listOf("Greek", "Latin")

    private val assetFiles = mapOf(
        "greek" to "vocabulary/greek_core_vocabulary.json",
        "latin" to "vocabulary/latin_core_vocabulary.json"
    )

    private val cache = mutableMapOf<String, List<VocabularyEntry>>()

    @Synchronized
    fun entries(context: Context, language: String): List<VocabularyEntry> {
        cache[language]?.let { return it }
        val file = assetFiles[language]
            ?: throw IllegalArgumentException("No vocabulary list for language '$language'")
        val json = context.assets.open(file).bufferedReader().use { it.readText() }
        val root = JSONObject(json)
        val array = root.getJSONArray("entries")
        val list = ArrayList<VocabularyEntry>(array.length())
        for (i in 0 until array.length()) {
            val o = array.getJSONObject(i)
            list.add(
                VocabularyEntry(
                    rank = o.getInt("rank"),
                    headword = o.getString("headword"),
                    lemma = o.getString("lemma"),
                    definition = o.getString("definition"),
                    pos = o.getString("pos"),
                    group = o.getString("group")
                )
            )
        }
        if (list.isEmpty()) throw IllegalStateException("$file contains no entries")
        val headwords = list.map { it.headword }
        if (headwords.size != headwords.toSet().size) {
            throw IllegalStateException("$file has duplicate headwords")
        }
        cache[language] = list
        return list
    }

    /**
     * Sets of [SET_SIZE] words in list order (the list is sorted by frequency
     * rank), followed by one set holding every word. Labels use list positions
     * rather than rank values because the sources assign some ranks twice.
     */

    /**
     * The form used to open the app dictionary: the lemma with macrons removed,
     * since dictionary headwords carry none. A no-op for Greek.
     */
    fun dictionaryForm(lemma: String): String {
        val decomposed = java.text.Normalizer.normalize(lemma, java.text.Normalizer.Form.NFD)
        return java.text.Normalizer.normalize(decomposed.replace("\u0304", ""), java.text.Normalizer.Form.NFC)
    }
    fun sets(context: Context, language: String): List<VocabularySet> {
        val all = entries(context, language)
        val sets = all.chunked(SET_SIZE).mapIndexed { i, chunk ->
            val first = i * SET_SIZE + 1
            val last = first + chunk.size - 1
            VocabularySet("Words $first–$last", chunk)
        }
        return sets + VocabularySet("All ${all.size} words", all)
    }
}
